# Site settings
title: BriOD Blog
header-img: img/home-bg.png
email: briodonoghue@gmail.com
copyright_name: BriOD
description: > # this means to ignore newlines until "baseurl:"
  A programming journey.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Bri__OD
github_username:  BriOD
learn_profile: BriOD
email_username: briodonoghue@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
